version: "2"
services:
  es-node0:
    image: elasticsearch:6.8.3
    container_name: es-node0
    mem_limit: 1g
    volumes:
      - ./node0/data:/usr/share/elasticsearch/data:rw
      - ./node0/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./node0/logs:/user/share/elasticsearch/logs:rw
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  es-node1:
    image: elasticsearch:6.8.3
    container_name: es-node1
    mem_limit: 1g
    volumes:
      - ./node1/data:/usr/share/elasticsearch/data:rw
      - ./node1/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./node1/logs:/user/share/elasticsearch/logs:rw
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  es-node2:
    image: elasticsearch:6.8.3
    container_name: es-node2
    mem_limit: 1g
    volumes:
      - ./node2/data:/usr/share/elasticsearch/data:rw
      - ./node2/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./node2/logs:/user/share/elasticsearch/logs:rw
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  es-head:
    image: tobias74/elasticsearch-head:6
    container_name: es-head
    mem_limit: 1g
  kibana:
    image: kibana:6.8.3
    container_name: kibana
    mem_limit: 1g
    environment:
      SERVER_NAME: localhost
      SERVER_BASEPATH: /kibana
      SERVER_REWRITEBASEPATH: "true"
      ELASTICSEARCH_URL: http://tengine:80/
  tengine:
    image: axizdkr/tengine:2.3.2
    container_name: tengine
    ports:
      - "9200:80"
    volumes:
      - ./tengine/logs:/var/log/nginx:rw
      - ./tengine/conf/conf.d:/etc/nginx/conf.d:ro
