version: "2"
services:
  es-master:
    image: elasticsearch:6.8.3
    container_name: es-master
    mem_limit: 2g
    volumes:
      - ./master/data:/usr/share/elasticsearch/data:rw
      - ./master/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./master/logs:/user/share/elasticsearch/logs:rw
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
  es-node1:
    image: elasticsearch:6.8.3
    container_name: es-node1
    mem_limit: 1g
    volumes:
      - ./node1/data:/usr/share/elasticsearch/data:rw
      - ./node1/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./node1/logs:/user/share/elasticsearch/logs:rw
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  es-node2:
    image: elasticsearch:6.8.3
    container_name: es-node2
    mem_limit: 1g
    volumes:
      - ./node2/data:/usr/share/elasticsearch/data:rw
      - ./node2/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./node2/logs:/user/share/elasticsearch/logs:rw
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  es-head:
    image: tobias74/elasticsearch-head:6
    container_name: es-head
    mem_limit: 1g
  kibana:
    image: kibana:6.8.3
    container_name: kibana
    mem_limit: 1g
    environment:
      SERVER_NAME: localhost
      SERVER_BASEPATH: /kibana
      SERVER_REWRITEBASEPATH: "true"
      ELASTICSEARCH_URL: http://proxy:80/
  nginx:
    image: nginx:1.16.1-alpine
    container_name: proxy
    ports:
      - "9200:80"
    volumes:
      - ./nginx/logs:/var/log/nginx:rw
      - ./nginx/conf/conf.d:/etc/nginx/conf.d:ro
